# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.github.reallyliri.limonitprogressbarplugin
pluginName = limonit-progress-bar
pluginVersion = 0.0.17

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild = 261
pluginUntilBuild = 261.*

# IntelliJ Platform Properties -> https://github.com/JetBrains/gradle-intellij-plugin#intellij-platform-properties
# https://www.jetbrains.com/intellij-repository/releases
platformType = IC
platformVersion = 2026.1

# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
platformPlugins =

javaVersion = 25

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 9.4.1

kotlin.stdlib.default.dependency=false
org.gradle.unsafe.configuration-cache=true
org.gradle.caching=true
